include:
  - ${DCM_CONFIG_DIR}/DcmPhp/Php74/volumes.yml

services:
  php74:
    build:
      context: ../../lib
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "7.4"
        UID: ${DCM_UID:-1000}
        GID: ${DCM_GID:-1000}
    image: dcm-php:7.4
    restart: unless-stopped
    volumes:
      - ${DCM_VOLUMES_DIR}/DcmPhp/apps:/var/www/html:z
      - ${DCM_VOLUMES_DIR}/DcmPhp/composer:/composer:z
    networks:
      - web
      - db
    depends_on:
      caddy:
        condition: service_started
